llm:
  model: anthropic
lint:
  enable: true
  commands:
    - command: "uv run ruff format --force-exclude --respect-gitignore"
      extensions: [".py"]
    - command: "uv run ruff check --fix --force-exclude"
      extensions: [".py"]
    - command: "prettier --write"
      extensions: [".md"]
    - command: "keep-sorted"
      extensions: ["*"]
files:
  ignore:
    - .byte/cache
    - .ruff_cache
    - .idea
    - .venv
    - .env
    - .git
    - .pytest_cache
    - __pycache__
    - node_modules
  watch:
    enable: true
web:
  enable: true
  chrome_binary_location: /etc/profiles/per-user/sincore/bin/google-chrome-stable
cli:
  ui_theme: mocha
  syntax_theme: github-dark
lsp:
  enable: true
  timeout: 30
  servers:
    python:
      command: ["uv", "run", "jedi-language-server"]
      file_extensions: ["py", "pyi"]
